name: Publish to npm

on:
  push:
    branches:
      - main # Change to your default branch if it's different

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.17.1' # Use the specified node version
          # cache: 'pnpm'

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.3.0' # Use the specified pnpm version

      - name: Install dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build

      - name: Configure npm for publishing
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_SECRET_KEY }}" > ~/.npmrc
          echo "NPM Token: ${{ secrets.NPM_SECRET_KEY }}" # This will print the token value
          
      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_SECRET_KEY }} # Use the specified secret key
        run: pnpm publish --access public
